### ISSUE TITLE
不能正确加载训练数据，而总是出现作者电脑的文件地址

### ISSUE THREAD

**Issue by houchenwang** [zipzou/captcha-recognition#19]
No such file or directory: '/Users/frank/Downloads/captchas/NJQE.jpg'
调试发现自从data.py调用了train.npy文件后，path就被赋值到了train.npy，随后x_train就被赋值成了一个array,array(['/Users/frank/Downloads/captchas/NJQE.jpg',
       '/Users/frank/Downloads/captchas/VNVB.jpg',
       '/Users/frank/Downloads/captchas/E3YH.jpg', ...,
       '/Users/frank/Downloads/captchas/AE3B.jpg',
       '/Users/frank/Downloads/captchas/HYGT.jpg',
       '/Users/frank/Downloads/captchas/WP2C.jpg'], dtype='<U40')
我希望从我的地址调用图片训练数据，本人不是很懂模型训练，但急需，望大佬释疑

**Comment by zipzou** [comment]
可以提供一下详细的执行脚本

**Comment by houchenwang** [comment]
python train.py -i  .\captchas -m kaptcha -o ./model -b 128
这是执行时用的命令，是指这个吗

**Comment by zipzou** [comment]
你的目录结构如何，现有的数据加载逻辑为：根据提供的数据目录，获取npy文件，若存在，则直接夹在npy数据，否则，列出该目录下所有的文件，并根据文件名作为label构建数据集，需要检查下目录结构是否正确。

**Comment by houchenwang** [comment]
<img width="952" alt="微信图片_20240601125136" src="https://github.com/zipzou/captcha-recognition/assets/139141978/0f741b64-e266-4f69-a5d9-402828069ff0">
这是我的目录结构，captchas里是我根据您的方法生成的一些验证码jpg文件，但程序似乎并未构建数据集

**Comment by zipzou** [comment]
默认情况下，会读取data下的npy文件，若需要重新根据自己的数据集，需要将data目录rename或清空。

**Comment by houchenwang** [comment]
谢谢您！现在能运行不报错了，但batch size设为128的情况下10min内进度条一直不动，这对于3080独显来说正常吗
![微信截图_20240601144320](https://github.com/zipzou/captcha-recognition/assets/139141978/96a41467-7ab0-46c7-8584-13d6afe03595)

**Comment by houchenwang** [comment]
可以了，原来tqdm不对，谢谢您
