### ISSUE TITLE
生成的图片全是大写的

### ISSUE THREAD

**Issue by Zero0719** [zipzou/captcha-recognition#7]
请教一下，执行了jar包以后生成的图片都是大写的，该怎么配置才能让他大小写都有呢

**Comment by zipzou** [comment]
> 请教一下，执行了jar包以后生成的图片都是大写的，该怎么配置才能让他大小写都有呢

EasyCaptcha只能生成大写字母，但是Kaptcha可生成小写字母，详情见`captcha-images/src/main/java/me/zouzhipeng/KaptchaGeneratorWorker.java`第43行。

执行时配置参数`-m kaptcha`即可。
